baseURL = "https://margaretmvaltierra.com"
languageCode = "en-us"
title = "Margaret Valtie"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""   

[taxonomies]
  tag = "tags"

[author]
	name = "mvaltie"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "A year of summer <p>I am a product of Nashville, a lover of New Orleans, and a proud Chicago transplant. I adore my dog, Peanut. I am an AWS Community Hero and I help build and run technical communities in Chicago. Since 2013, I've organized the [Chicago AWS user group](https://chicagoaws.com/). In 2017 I joined the wonderful [DevOpsDays Chicago](https://www.devopsdays.org/chicago) organizers; I convince awesome companies to send their best and brightest to Chicago in the summertime.<p> This is my personal blog and former travelog."

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "mailto:yaamargie@gmail.com"
    twitter = "https://www.twitter.com/margaretvaltie"
	linkedin = "https://www.linkedin.com/in/margaretvaltierra/"

	# Programming
    github = "https://github.com/margaretvaltie"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "resume"
	name = "Resume"
	url = "https://s3-us-west-2.amazonaws.com/www.margaretmvaltierra.com/Margaret-Valtierra-resume.pdf"
	weight = 2

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 3

[[menu.main]]
	name = "Twi for Obruni"
	identifier = "twi"
	url = "/twi/"
	weight = 4	


# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true